branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt
script:
- rm -rf .git/
- git init
- git config user.name "huongnhdh"
- git config user.email "huong.nhdh@gmail.com"
- git remote add origin https://${GH_TOKEN}@github.com/huongnhdh/wiki.git
- make github
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
    secure: 4fmtuXvWvJei+jZkTJMZT2nwEoz6KCTxmlyayR2cqb1Jx0l3A4TGtco9mGzkKDORLG7Bg8QlnljbZPsWrtD0cM+teUZL/EKtrpuuf2UV06ZXtEatf2nampgHeDy/rfcptYfTyhk9W72hFYKlmUiLue4R2A9sejccwcYdyaDQUCByL4Ocem6/01eDin0Xzb8xy32kjXLtIaxemLIcxtmacbrJsYiTP2wDCOCOMIJn0BM0hoeRiRjI4neX88wp3L9Q/Krif25qlVqq4NsjaYG7ZMxU8a69AkYu71cUj2znwJtgGceYwCazJnbMQwJS9PONGyIHYBOWur+Y/2/H1cWiUZ/UESLtNcgU2MI1d2uc2jcpcCrUW8FaL6E86f8gpJfyu9kEyOxoEguo8E8a0I8rxfbpyIIkYggdShjZLmpHm2HPMzTM1Z+AHdFptZwKO8033344Jpu4zKWbeUZld5reZdAkEU/afSUtDFvQ1qTVZXpewsSjU1rAwfcxnhi9KmIvst30ZS4zCcTFJ0SI1OcWwL/n36D0Cd7cn0zenKpdU2/SsFBD2+Jq6+WWYUUx4XuzqfQ4/NYcv8UsrgZRh+KoOiKQCbtNXAsciNQi+IQT4HFq89B6ND9uXHxvfE8hVKKq+4AtmoGAdbfHJv0yQ8A6OKxXNNNMZ4nEOyzQ7QgwveI=
# before_install:
# - git submodule update --init --recursive